module.exports = {
    darkMode: "class",
    theme: {
        extend: {
            colors: {
                primary: "#ffb59c",
                "primary-fixed-dim": "#ffb59c",
                "inverse-on-surface": "#2c3138",
                "on-primary-fixed": "#390c00",
                "on-secondary-fixed-variant": "#0038b6",
                surface: "#11161d",
                "surface-container-low": "#171c23",
                "surface-container-lowest": "#090f15",
                "surface-container": "#1b2027",
                "surface-container-high": "#20252d",
                "surface-container-highest": "#30353d",
                "surface-variant": "#30353d",
                "surface-tint": "#ffb59c",
                "surface-dim": "#0f141a",
                "on-error-container": "#ffdad6",
                "outline-variant": "#5c4037",
                outline: "#ac897e",
                "on-tertiary-container": "#252a31",
                "secondary-fixed-dim": "#b7c4ff",
                "secondary-container": "#0040cb",
                "tertiary-fixed": "#dee3eb",
                "primary-fixed": "#ffdbcf",
                "on-background": "#dee2ec",
                "on-surface-variant": "#e5beb2",
                "brand-orange": "#ff5400",
                "brand-blue": "#1e4ed8",
                "on-primary-container": "#511500",
                "tertiary-container": "#8c9199",
                "primary-container": "#ff570b",
                tertiary: "#c2c7cf",
                "on-error": "#690005",
                "on-primary": "#5c1900",
                "on-secondary-container": "#b2c0ff",
                "on-tertiary": "#2c3137",
                "error-container": "#93000a",
                background: "#0f141a",
                "inverse-surface": "#dee2ec",
                "on-primary-fixed-variant": "#832700",
                "secondary-fixed": "#dce1ff",
                "tertiary-fixed-dim": "#c2c7cf",
                "on-tertiary-fixed": "#171c22",
                "on-tertiary-fixed-variant": "#42474e",
                "on-surface": "#dee2ec",
                secondary: "#b7c4ff",
                "on-secondary": "#002682"
            },
            borderRadius: {
                DEFAULT: "0.125rem",
                lg: "0.25rem",
                xl: "0.5rem",
                full: "0.75rem"
            },
            spacing: {
                gutter: "24px",
                xs: "8px",
                sm: "16px",
                md: "24px",
                lg: "48px",
                xl: "80px",
                base: "4px",
                "margin-mobile": "16px",
                "margin-desktop": "64px"
            },
            fontFamily: {
                "label-md": ["JetBrains Mono", "monospace"],
                "label-sm": ["JetBrains Mono", "monospace"],
                "display-lg-mobile": ["Space Grotesk", "sans-serif"],
                "display-lg": ["Space Grotesk", "sans-serif"],
                "headline-md": ["Space Grotesk", "sans-serif"],
                "headline-lg": ["Space Grotesk", "sans-serif"],
                "headline-sm": ["Space Grotesk", "sans-serif"],
                "body-lg": ["Inter", "sans-serif"],
                "body-md": ["Inter", "sans-serif"],
                "body-sm": ["Inter", "sans-serif"]
            },
            fontSize: {
                "label-md": ["14px", { lineHeight: "16px", fontWeight: "500" }],
                "label-sm": ["12px", { lineHeight: "14px", fontWeight: "500" }],
                "display-lg-mobile": ["40px", { lineHeight: "44px", fontWeight: "700" }],
                "display-lg": ["64px", { lineHeight: "72px", letterSpacing: "-0.02em", fontWeight: "700" }],
                "headline-md": ["32px", { lineHeight: "40px", fontWeight: "600" }],
                "headline-lg": ["40px", { lineHeight: "48px", fontWeight: "600" }],
                "headline-sm": ["24px", { lineHeight: "32px", fontWeight: "600" }],
                "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
                "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
                "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }]
            }
        }
    }
};
